### PR TITLE
Adding a CORSHandler to the proj_template.

### PR DESCRIPTION
**Pull request by russ**
The settings are friendly to local development and include a place for
production domains as well (the code comes from here: https://luckyframework.org/guides/json-and-apis/cors)

It doesn't have to be included but it helps to get things going.

### CODE REVIEW

**Comment by KCErb** [comment]
Looks awesome @russ thanks for submitting!

I'm tempted to have it go in a lower section of the TLDR where I'm trying to keep the optional / goodies. The goal is to keep minimize the number of steps from 0 to up in that document.

That being said, I've been pasting 'optional' code directly into the guide/tldr but that pattern doesn't scale well. Eventually I'd like to have a generator where you can have more control over the template / boilerplate that you pull in.

So that leaves me between a few options and I could be easily persuaded as to which is optimal.

1. Move the TLDR instruction down into its own bottom section about CORS and paste your file into the guide for users to copy/create on their own sorta like we do for `query_spec.cr` in the `Seed Database, Test Lucky, Test Hasura` section.

2. Leave it where it is in the TLDR (and as a file that is copied into the project) and treat it as essential / mandatory.

3. Come up with the right way to scale the templating / boilerplating to accommodate different preferences.

I vote for approach 1 if this feels optional / nice to have to you @russ (and others).
I vote for approach 2 if this feels necessary for a basic dev experience.

**Comment by russ** [comment]
I'm going to go with option 1 to keep things simple for right now. Having the simple rsync is really nice when setting up a new project, and you really only do it once. I'll get this pull updated with that.

**Comment by KCErb** [comment]
OK cool, sounds good to me. For consistency, we should paste the same snippet in both places (another area for improvement since it can be a hassle to have duplicate content between the TLDR and the GUIDE).

If you want to give that another commit that's fine, otherwise I'll take care of it tomorrow.

**Comment by russ** [comment]
Lol. I stared at the screen for a while with it in both places before
taking it out. I’ll throw it back in in the morning.

**Comment by KCErb** [comment]
Hi @russ I added some more text to the guide part and added a step asking people to 'require' the handlers dir in `app.cr`.

If that works for you I'll go ahead and merge :)

**Comment by russ** [comment]
Sounds good. Works for me!

**Pull request merged**
